### ISSUE TITLE
Error when running local-ai script

### ISSUE THREAD

**Issue by pehaem** [aorumbayev/autogpt4all#13] opened 2023-06-16 22:10 UTC
./local-ai --models-path ./models/ --debug
-bash: ./local-ai: No such file or directory

missing local-ai script?

**Comment by aorumbayev** [comment] 2023-06-16 22:20
You running on Linux? For some reason it skips the make build steps in localai repo I'll debug later or feel free to submit a pr it's probably just a matter of adding additional conditional check. 

Otherwise it's a duplicate of:
https://github.com/aorumbayev/autogpt4all/issues/11#issuecomment-1591297392

**Closed as completed** 2023-06-16 22:20 UTC
